### ISSUE TITLE
Error initializing device

### ISSUE THREAD

**Issue by fooons** [dfelinto/virtual_reality_viewport#16] opened 2015-12-08 11:46 UTC
Hi, I am using Blender 2.76b on OS X El Capitan 10.11.1 with a DK1 and I receive this error when I click on Start.
<img width="1324" alt="captura de pantalla 2015-12-08 a las 12 18 16" src="https://cloud.githubusercontent.com/assets/11136798/11654783/77a5d9b8-9da8-11e5-82d7-507d78f8183f.png">
The version of the add-on was downloaded from: 
http://www.dalaifelinto.com/ftp/builds/space_view3d_virtual_reality.zip

When I download the add-on from latest Github I get this one:
<img width="779" alt="captura de pantalla 2015-12-08 a las 12 43 22" src="https://cloud.githubusercontent.com/assets/11136798/11654899/80a30ea4-9da9-11e5-8a6f-9cca471668d7.png">

**Comment by dfelinto** [comment] 2015-12-08 11:48
The problem is the version of Blender that you are using. Get a "under development" Blender 2.77 from https://builder.blender.org/download

**Comment by dfelinto** [comment] 2015-12-08 11:48
Since this is mentioned in the README page of the repository I'll go ahead and close this issue. Let me know if you still run into problems though.

**Closed as completed by dfelinto** 2015-12-08 11:48 UTC

**Comment by fooons** [comment] 2015-12-08 13:22
Hi,all is working fine now. My mistake was search for a 2.77 version in the builder page. The latest versions are blender-2.76-964107f-OSX-10.6-x86_64 so I was confused and no download it.
Thanks.
